### ISSUE TITLE
Internal Server Error while registering

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#931]
**Describe the bug**
While creating a new user, I got internal server error due to some constraint violations

**To Reproduce**
Not able to reproduce

**Expected behavior**
It should give error message instead of server error
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.0.4
 - Browser [e.g. chrome, safari] Chromium

**Comment by devkapilbansal** [comment]
Here is the traceback in backend that I got:-

**TLDR**

```
127.0.0.1 - - [29/Nov/2020 23:47:47] "POST /register HTTP/1.1" 201 -
127.0.0.1 - - [29/Nov/2020 23:47:48] "POST /register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    self.dialect.do_execute(
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_username_key"
DETAIL:  Key (username)=(nuuser) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kapil/.local/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kapil/.local/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/kapil/.local/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/kapil/Development/ANITA-B/mentorship-backend/app/api/resources/user.py", line 320, in post
    result = DAO.create_user(data)
  File "/home/kapil/Development/ANITA-B/mentorship-backend/app/api/dao/user.py", line 74, in create_user
    user.save_to_db()
  File "/home/kapil/Development/ANITA-B/mentorship-backend/app/database/models/user.py", line 152, in save_to_db
    db.session.commit()
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 553, in execute
    persistence.save_obj(self.mapper,
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 179, in save_obj
    _emit_insert_statements(base_mapper, uowtransaction,
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 865, in _emit_insert_statements
    result = cached_connections[connection].\
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1055, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1195, in _execute_context
    self._handle_dbapi_exception(
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1411, in _handle_dbapi_exception
    util.raise_from_cause(
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    self.dialect.do_execute(
  File "/home/kapil/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_username_key"
DETAIL:  Key (username)=(nuuser) already exists.
 [SQL: 'INSERT INTO users (name, username, email, password_hash, registration_date, terms_and_conditions_checked, is_admin, is_email_verified, email_verification_date, current_mentorship_role, membership_status, bio, location, occupation, organization, slack_username, social_media_links, skills, interests, resume_url, photo_url, need_mentoring, available_to_mentor) VALUES (%(name)s, %(username)s, %(email)s, %(password_hash)s, %(registration_date)s, %(terms_and_conditions_checked)s, %(is_admin)s, %(is_email_verified)s, %(email_verification_date)s, %(current_mentorship_role)s, %(membership_status)s, %(bio)s, %(location)s, %(occupation)s, %(organization)s, %(slack_username)s, %(social_media_links)s, %(skills)s, %(interests)s, %(resume_url)s, %(photo_url)s, %(need_mentoring)s, %(available_to_mentor)s) RETURNING users.id'] [parameters: {'name': 'new user', 'username': 'nuuser', 'email': 'nuuser@gmail.com', 'password_hash': 'pbkdf2:sha256:150000$mbC3vqB1$824e3fd6882975f861ddc2e7cf250479b78b9b8306c90f97d078dbec5e6482d1', 'registration_date': 1606673867.2491403, 'terms_and_conditions_checked': True, 'is_admin': False, 'is_email_verified': False, 'email_verification_date': None, 'current_mentorship_role': None, 'membership_status': None, 'bio': None, 'location': None, 'occupation': None, 'organization': None, 'slack_username': None, 'social_media_links': None, 'skills': None, 'interests': None, 'resume_url': None, 'photo_url': None, 'need_mentoring': True, 'available_to_mentor': True}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by devkapilbansal** [comment]
It would be great if someone can try and reproduce this error

**Comment by isabelcosta** [comment]
@devkapilbansal it would be interesting to know the conditions in which you got this. Like, which data you used to register a user 🤔 like POST data (without revealing anything you think should be private).Thank you for reporting this anyways, even if you can't reproduce, someone can still look into this 🙌

**Comment by vj-codes** [comment]
@devkapilbansal hey is this issue resolved ?You have used duplicate key value and probably an error by psycopg2 .
Can you try keeping all values unique ? If it still throws the same error do share the data as suggested above

**Comment by devkapilbansal** [comment]
Yes, @vj-codes I used duplicate keys but instead of a 400( bad request), it gives me internal server error. Also, data as asked by @isabelcosta is already there in the last line of error. My main concern was that it can leak potential information to end user.
Also, as I am not able to retrace it and it may be due to the dependencies issues that has been solved now. It is safe to close it.
